Remove alias git cl
Sometimes it barfs out an error (see below) and I don't use it anyway so
let's just zap it instead of fixing.

-e:1:in `block in <main>': undefined method `[]' for nil:NilClass (NoMethodError)
        from -e:1:in `each'
        from -e:1:in `<main>'